
try(require(shiny) || install.packages("shiny"))
try(require(text2vec) || install.packages("text2vec"))
try(require(tm) || install.packages("tm"))
try(require(tokenizers) || install.packages("tokenizers"))
try(require(wordcloud) || install.packages("wordcloud"))
try(require(slam) || install.packages("slam"))

try(require(stringi) || install.packages("stringi"))
try(require(magrittr) || install.packages("magrittr"))
try(require(tidytext) || install.packages("tidytext"))
try(require(dplyr) || install.packages("dplyr"))
try(require(tidyr) || install.packages("tidyr"))
try(require(stringr)|| install.packages("stringr"))
try(require(udpipe)|| install.packages("udpipe"))
try(require(textrank)|| install.packages("textrank"))
try(require(lattice)|| install.packages("lattice"))
try(require(igraph)|| install.packages("igraph"))
try(require(ggraph)|| install.packages("ggraph"))
try(require(ggplot2)|| install.packages("ggplot2"))

library(shiny)
library(text2vec)
library(tm)
library(tokenizers)
library(wordcloud)
library(slam)
library(stringi)
library(magrittr)
library(tidytext)
library(dplyr)
library(tidyr)
library(stringr)
library(udpipe)
library(textrank)
library(lattice)
library(igraph)
library(ggraph)
library(ggplot2)
